### ISSUE TITLE
[bug] No waiting status

### ISSUE THREAD

**Issue by jwkim1993** [tmax-cloud/approval-watcher#26]
## Actual Behavior

Even though there is a approval step waiting to be approved, the approval CR has no "Waiting" status.

![image](https://user-images.githubusercontent.com/59426033/87751978-3b7e1b00-c83a-11ea-9126-fb1f6239eac1.png)

 ## Expected Behavior

There should be "Waiting" status in the approval CR

**Comment by cqbqdd11519** [comment]
Status를 포함해서 create해도 저장될땐 Status가 없이 저장되더라구요
Create이후 따로 Status update를 해줘야할 것 같습니다

이때 동기화 이슈가 발생할것같아서 넣지 않았는데 포함하도록 하겠습니다

**Comment by jwkim1993** [comment]
그러면 그냥 Waiting을 제외할까요?? Waiting인 경우 없어도 될 것 같기도 해서요. 어떻게 생각하시나요.

**Comment by cqbqdd11519** [comment]
명시적으로 Waiting 상태라는걸 보여주긴 해야할 것 같아요

동기화 이슈는 쿠베 api서버가 알아서 핸들해주겠죠ㅎㅎ
